### ISSUE TITLE
while dragging the imageview in the viewpager in zoom mode,the image can not be fully shown.

### ISSUE THREAD

**Issue by snowdream** [Baseflow/PhotoView#148]
My project is https://github.com/snowdream/android-imageviewer
i use the photoview with Android-Universal-Image-Loader.   (viewpager)

Setp:
1.in normal mode. 
when i drag the imageview,it's fine.
![1](https://f.cloud.github.com/assets/737958/2107701/691000f0-8fd0-11e3-88aa-e63e9cb3c619.png)

2.in zoom mode
i double tap the second,and drag it .
the image can not be fully shown.

![2](https://f.cloud.github.com/assets/737958/2107772/ace3a506-8fd1-11e3-9a90-80c6209be0e7.png)

**Comment by hfkai** [comment]
Hi,How to customize with this？
