### ISSUE TITLE
Add pin marks over image

### ISSUE THREAD

**Issue by matheusjardimb** [Baseflow/PhotoView#179]
It'd be great if one can insert a list of view over the image view (an experience similar to a map viewer).

**Comment by atonamy** [comment]
@smarek if it's not difficult for you could you please give some sample code [here](https://stackoverflow.com/questions/48850076/photoview-calculate-appropriate-coordinates-of-pin-tile-view-depending-of-disp) to explain who exactly displayed matrix can use to render some pin view on top of PhotoView. If you you already implemented OnMatrixChangedListener please explain how exactly to use it for such task like pin marks over image.
