### ISSUE TITLE
Programmatically Move around a picture.

### ISSUE THREAD

**Issue by adfleshner** [Baseflow/PhotoView#185]
Am I able to Programmatically move around a picture that I have zoomed in on? So that I could zoom in on a picture and then move over to a point in the picture?

**Comment by NirpE** [comment]
I am not able to get this work, can you post small example? Using version 1.2.4 with scaleType center and trying following to get it scrolled top:
<code>

    @Override
    public void setImageBitmap(Bitmap bm) {
        super.setImageBitmap(bm);

        try {
            Matrix m = getDisplayMatrix();

            float values[] = new float[9];
            m.getValues(values);
            m.postTranslate(0f, values[5] * -1);

            setDisplayMatrix(m);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
</code>

**Comment by NirpE** [comment]
I am not able to get this to work, when would it be the right time to call setDisplayMatrix?
