### ISSUE TITLE
i could not import the library

### ISSUE THREAD

**Issue by Asthme** [Baseflow/PhotoView#195]
Error:Could not find property 'plugin' on com.android.build.gradle.LibraryExtension_Decorated@5e34222f.

**Comment by mohsenzamani22** [comment]
Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.1] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:33:5-314:19 to override.
