### ISSUE TITLE
Could not change background to transparent

### ISSUE THREAD

**Issue by ntanduc2288** [Baseflow/PhotoView#201]
How can i change background to transparent, i'd tried "android:background="@color/transparent" but nothing happen

<<uk.co.senab.photoview.PhotoView
        android:id="@+id/imgView"
        android:layout_width="fill_parent"
        android:layout_height="fill_parent"
        android:background="@color/transparent"
        android:src="@drawable/image"
         />

**Comment by weituotian** [comment]
@smarek could not work!
how about layout width and layout height is match parent!
