### ISSUE TITLE
Set min and max zoom/scale level

### ISSUE THREAD

**Issue by hameno** [Baseflow/PhotoView#24]
First: great library! 

Is there a possibility to set the min and max zoom level? Currently it reverts to a min zoom level defined by the views bounds.

**Comment by jezielti** [comment]
PhotoViewAttacher photoView = new PhotoViewAttacher(img);
photoView.setMaximumScale(10);

**Comment by galcyurio** [comment]
We can use also `PhotoView#setMaximumScale()`
