### ISSUE TITLE
Is it possible to disable the ViewPage while in zoom?

### ISSUE THREAD

**Issue by juliocbcotta** [Baseflow/PhotoView#27]
Hi, I would like to know if you can help me.
I have a ViewPager working with the PhotoView, but I would like to disable the ViewPager Scroll while the PhotoView is in the zoom mode.
Could you please show me the path?
Thanks in advance.

**Comment by MallikarjunaSH** [comment]
Even i have the same problem please help me @chrisbanes

**Comment by vsay01** [comment]
@MallikarjunaSH @BugsBunnyBR you can try the solution provided [here](https://github.com/chrisbanes/PhotoView/issues/574)

**Comment by HGilman** [comment]
Yes it is possible
You should make custom ViewPager and ovveride canScroll functions like this
`
class ImageViewerViewPager @JvmOverloads constructor(context: Context, attrs: AttributeSet? = null)
    : IllegalArgumentExceptionInterceptorViewPager (context, attrs) {


    /*
    * if current image is zoomed then view pager doesn't make scroll
    *  (but it seems strange for me that it return trues in this case)
    * */
    override fun canScroll(v: View, checkV: Boolean, dx: Int, x: Int, y: Int): Boolean {
        val currentView = findViewWithTag<PhotoView>(currentItem)
        return if (currentView.scale > currentView.minimumScale) {
            true
        } else {
            return super.canScroll(v, checkV, dx, x, y)
        }
    }
}`
