### ISSUE TITLE
 ImageView no longer exists. You should not use this PhotoViewAttacher any more.

### ISSUE THREAD

**Issue by fanei** [Baseflow/PhotoView#50]
05-02 17:21:59.583: E/AndroidRuntime(6325): FATAL EXCEPTION: main
05-02 17:21:59.583: E/AndroidRuntime(6325): java.lang.IllegalStateException: ImageView no longer exists. You should not use this PhotoViewAttacher any more.
05-02 17:21:59.583: E/AndroidRuntime(6325):     at com.yijian.app.view.photoview.PhotoViewAttacher.getImageView(PhotoViewAttacher.java:210)
05-02 17:21:59.583: E/AndroidRuntime(6325):     at com.yijian.app.view.photoview.PhotoViewAttacher.update(PhotoViewAttacher.java:482)
05-02 17:21:59.583: E/AndroidRuntime(6325):     at com.yijian.app.view.photoview.PhotoView.setImageDrawable(PhotoView.java:114)
05-02 17:21:59.583: E/AndroidRuntime(6325):     at android.widget.ImageView.setImageBitmap(ImageView.java:377)
05-02 17:21:59.583: E/AndroidRuntime(6325):     at com.yijian.app.activity.GalleryActivity$TestAdapter$1.onLoadingComplete(GalleryActivity.java:287)
05-02 17:21:59.583: E/AndroidRuntime(6325):     at com.nostra13.universalimageloader.core.DisplayBitmapTask.run(DisplayBitmapTask.java:64)
05-02 17:21:59.583: E/AndroidRuntime(6325):     at android.os.Handler.handleCallback(Handler.java:605)
05-02 17:21:59.583: E/AndroidRuntime(6325):     at android.os.Handler.dispatchMessage(Handler.java:92)
05-02 17:21:59.583: E/AndroidRuntime(6325):     at android.os.Looper.loop(Looper.java:137)
05-02 17:21:59.583: E/AndroidRuntime(6325):     at android.app.ActivityThread.main(ActivityThread.java:4424)
05-02 17:21:59.583: E/AndroidRuntime(6325):     at java.lang.reflect.Method.invokeNative(Native Method)
05-02 17:21:59.583: E/AndroidRuntime(6325):     at java.lang.reflect.Method.invoke(Method.java:511)
05-02 17:21:59.583: E/AndroidRuntime(6325):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:787)
05-02 17:21:59.583: E/AndroidRuntime(6325):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:554)
05-02 17:21:59.583: E/AndroidRuntime(6325):     at dalvik.system.NativeStart.main(Native Method)

**Comment by mybslj** [comment]
@saimr It's still oocurring!

**Comment by arlindiDev** [comment]
There is no mViewTreeObserver field?

**Comment by Silence2016** [comment]
i have replace the cleanup function but there is no mViewTreeObserver field,where does it is decareed

**Comment by UshioYu** [comment]
Where is mViewTreeObserver?????I can't  find it.Could anyone can help me??

**Comment by aerb** [comment]
Think I'm seeing a similar issue on  `1.2.4`, PhotoView spams my log with:
`PhotoViewAttacher: ImageView no longer exists. You should not use this PhotoViewAttacher any more.`, even though I've called cleanup.

I also found that it was not correctly removing itself form the ViewTreeObserver. For future reference to anyone with the problem the quick-and-dirty fix was:
```java
attacher.cleanup();
getViewTreeObserver().removeOnGlobalLayoutListener(attacher);
```
