### ISSUE TITLE
Any support for animated gif?

### ISSUE THREAD

**Issue by macpraveen** [Baseflow/PhotoView#54]
Thanks for the wonderful library. Will there be any support for animated gif in the near future?

**Comment by Hitexroid** [comment]
The Best solution is [https://github.com/koral--/android-gif-drawable](url)

`                GifDrawable gif = null;
                try {
                    gif = new GifDrawable(CurrentPath);
                } catch (IOException e) {
                    e.printStackTrace();
                }
                photoView.setImageDrawable(gif);`

**Comment by JoyHong** [comment]
@Hitexroid No use.

**Comment by percula** [comment]
Using Glide, you can load a gif into PhotoView: https://github.com/bumptech/glide/wiki#whats-new-in-30

**Comment by Marfars** [comment]
> 

it's work. thanks
