### ISSUE TITLE
Bug: Can't open animated GIF/WEBP, not even as a normal photo

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Baseflow/PhotoView#685]
It should support opening those, even for the first frame.
When we decode those into a bitmap, we get the first frame. 
Library should support at least that.

**Comment by AndroidDeveloperLB** [comment]
Why close it?
It's a bug...

**Comment by AndroidDeveloperLB** [comment]
Animated image files are still image files. Should be able to open and view them, even if it means not as animation...

**Comment by Jawnnypoo** [comment]
It is a feature request, not a bug. And you could always download the first frame of the video/gif manually, it is not something that needs to be done in this library. It is beyond the scope of PhotoView, just as downloading and displaying images from the network is.

**Comment by AndroidDeveloperLB** [comment]
never mind. I tried the wrong repo. It's on a different repo
