### ISSUE TITLE
How to get Bitmap from the PhotoView

### ISSUE THREAD

**Issue by kpradeepkumarreddy** [Baseflow/PhotoView#797]
How to get Bitmap from the PhotoView ?
Image is set to PhotoView using Glide. 
Now, how can i get the Bitmap ?

**Comment by pradeep-orbi** [comment]
Using glide to get it

 Glide.with(this).asBitmap().load(fileUrl)
                .into(object : CustomTarget<Bitmap?>() {
                    override fun onResourceReady(
                        bitmap: Bitmap,
                        transition: com.bumptech.glide.request.transition.Transition<in Bitmap?>?
                    ) {
                      }
